services:
  xtream_diamonds:
    container_name: xtream_diamonds
    restart: always
    env_file:
      - .env
    build:
      context: .
      dockerfile: Dockerfile
    expose:
      - "${PORT}"
    ports:
      - "0.0.0.0:${PORT}:${PORT}"
      
    command: uvicorn main:app --reload --host 0.0.0.0 --port ${PORT}